### ISSUE TITLE
Unable to cure Pregnancy vaginosis

### ISSUE THREAD

**Issue by Mx772** [MacNaab/ProjectHospital_Gynecology#2]
I've had a few patients who get Pregnancy vaginosis which is cured with Antibiotics. However... it seems that for whatever reason, no where wants to give her them?

![image](https://user-images.githubusercontent.com/9059161/129459358-d9b7b0a9-09fb-4ae5-a988-d9cc863368d7.png)

I couldn't find what could be restricting these out of this small list:
Realistic Collapses and Disease Incidence
Medical Procedures
Additional Insurance Providers
Department of Gynecology and Obstetrics
Community Resource Pack
Bedside Examinations
More Levels

Sending her to Urgent Clinic also just redirects to Gyno which just notes they don't have it?

Maybe I'm missing something here?

Other diagnoses that require antibiotics outside of OBGYN seem to work, just not the ones inside of it?

**Comment by MacNaab** [comment]
That's strange, I'll take a look.
Maybe it's because the game wants you to cure RH- Symptom (high risk SYM).

Can you check the logs at
- Win: C:\Users\USERNAME\AppData\LocalLow\Oxymoron Games\Project Hospital\output_log.txt
- If you have problem accessing the hidden AppData folder, try entering %AppData% in windows explorer
- Linux: /home/USERNAME/.config/unity3d/Oxymoron Games/Project Hospital/Player.log 
- Mac: ~/Library/Logs/Unity/Player.log

**Comment by Mx772** [comment]
I think you got it. It is trying to treat the RH- Symptom. 

After adding ICU + Hospitalization it sent them there and haven't seen it since.
